### ISSUE TITLE
Allow indexing of a single gene in PRG and add a merge function to combine indexes

### ISSUE THREAD

**Issue by rmcolq** [rmcolq/pandora#105]
Need to consider that at the moment the PRG_id stored in the index is the position in the PRG file, and some sort of unique id for each PRG needs to be kept through the merge process (could be a name instead of an id)

**Comment by leoisl** [comment]
Is this already implemented? I see https://github.com/rmcolq/pandora/blob/7adf63ce60d28a000f7b6c850f4a5ebbbf2dd031/src/main.cpp#L51
which seems to indicate it is...

**Comment by rmcolq** [comment]
Assuming that the correct PRG ids have been set using --offset when running `index` on PRG files, can merge them. This was a quickly implemented thing though, with no catches for user error. e.g. if the new index has entries with the same PRG id, adds them anyway

**Comment by rmcolq** [comment]
i.e. this function performs a naive merge of two indexes, appending one to the other with no checks

**Comment by leoisl** [comment]
Ok! This was mainly done to merge the output of several `index` with nextflow/snakemake or is there another use case?

**Comment by rmcolq** [comment]
Exactly! e.g. I have a nextflow script in `/nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/index_prg.nf`

**Comment by rmcolq** [comment]
I think this is now defunct. Given the speed up of indexing, no longer necessary. Can be reopened if we want something similar again.
