### ISSUE TITLE
Error indexing PRG

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#111]
I seem to have triggered the following error lines in indexing https://github.com/mbhall88/pandora/blob/5786548a1a1111a4990f0b8a6ec3335e4d1a5319/src/localPRG.cpp#L204-L209

The error arose when trying to index using 

```sh
cd /hps/nobackup/iqbal/mbhall/Pandora_variation/Analysis/Cardio/Assess_local_assembly/data/H152180645/pandora_index
prg=$(realpath ../make_prg/H152180645_prgs.fa)
mem=30
bsub.py "$mem" pandora_index pandora index "$prg"
```

The error output shows

```
In conversion from linear localPRG string to graph, splitting the string by the next var site
resulted in the wrong number of intervals. Perhaps ordering of numbers in GFA is irregular?!
Size of partition based on site 29 is 3
```

**Comment by rmcolq** [comment]
How did you generate the PRG file? (as in how did you merge your new PRGs and the old ones?) There is no space sandwiching either side of the number in places where there is a `G29`, the first two examples of these is in `GC00007068_2`, `GC00004441_3`. These are both genes which have not been updated, and there is no problem in `/nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa` which is where you must have copied them from, so I'm not sure how the space has been removed?

**Comment by mbhall88** [comment]
Ah. That must be from Martin's `fastaq` python library. It outputs multi-line fasta so I converted it to single line fasta with one of his tools and it obviously doesn't keep spacing (as not a normal fasta spec.).
Will have to do it another way.

**Comment by rmcolq** [comment]
Pandora will probably cope with multiline fasta - it makes no assumptions about single line (read files often aren't) or consistent line lengths

**Comment by mbhall88** [comment]
Yeah, but I guess when it is converted to multi-line the spaces can be messed up when it breaks the sequence into lines?

**Comment by rmcolq** [comment]
Oh ok - I thought you meant that the script to convert from multiline to single line was the problem, but if not then my comment is not relevant!

**Comment by mbhall88** [comment]
Well I don't know which one it was.   
Anyway, I wrote a python script to combine the PRGs and it seems to be running all ok now. Will close once that job completes.

**Comment by rmcolq** [comment]
This was an issue with spacing in the input PRG. I've updated the error message to recommend checking PRG file for this spacing in commit 947f48406ae130ca3db7df6cd9dae0f4f3e17bd4
