### ISSUE TITLE
Crazy RAM use

### ISSUE THREAD

**Issue by rmcolq** [rmcolq/pandora#13]
Here is a quick excel graph showing for some values of coverage (x-axis) the time, max memory (RAM in MB) and average memory used by pandora.
![image](https://user-images.githubusercontent.com/9866043/38620019-667d0bcc-3d95-11e8-997d-f7a0b2333ee3.png)
To be updated with a better graph and extended to 900x (since we have the dataset for it.
Note that max RAM seems to grow linearly with coverage.

**Comment by leoisl** [comment]
hello,
1 year since the last comment on this issue. I am currently working on pandora map, I'd like to know if this is still an issue or not.

**Comment by rmcolq** [comment]
![image](https://user-images.githubusercontent.com/9866043/58267398-73471b00-7d7b-11e9-9581-dd2f506df984.png)
RAM is definitely still an issue for pandora map. It's low enough that the RAM requirement doesn't stop us being able to run map on the cluster, but is WAY higher than it should be. Plus, most improvements to RAM use in map will also improve them in compare, where it's a major bottleneck.

**Comment by iqbal-lab** [comment]
Agreed. I think @rmcolq has documented elsewhere on another issue suggested places where ram could be reduced by not duplicating stuff, mini hits or somewhere

**Comment by leoisl** [comment]
I think this is the issue you mentioned Zam: #131 , which is partly addressed already.

I am aware that the RAM is an issue for `map` and `compare`, I was just wondering if what was depicted earlier in this thread (1 year ago) was still the current scenario, which seems so.

@rmcolq : could you tell me which input did you use to make these plots? It would be nice to use them to  check if RAM usage was improved with the recent commits. I'd also appreciate a script to generate them, if you have (if it is hard to find, don't bother, I will do it)!

**Comment by rmcolq** [comment]
Nextflow script here:
```
/nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/scaling_by_covg.nf
```
Example command line:
```
bsub.py 2.0 /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/logs/scaling_by_covg nextflow run /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/scaling_by_covg.nf --pangenome_prg /nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_all/ecoli_pangenome_PRG_290818.fa --nanopore_reads /hps/nobackup/iqbal/mbhall/Pandora_variation/Data/Loman_K12/loman_k12_pass_porechop.fastq.gz --illumina_reads /nfs/leia/research/iqbal/rmcolq/data/loman_k12/Ecoli_S1_L001_R2_001.fastq.gz --final_outdir /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/scaling_by_covg/ -w /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/analysis/scaling_by_covg/work -c /nfs/leia/research/iqbal/rmcolq/git/DPhil_analysis/nextflow/nextflow.config -resume
```

**Comment by rmcolq** [comment]
Defunct - RAM now much more awesome
