### ISSUE TITLE
Improve minihits RAM use

### ISSUE THREAD

**Issue by rmcolq** [rmcolq/pandora#131]
As discussed, here are some ideas for reducing the RAM of quasimapping by improving the minhit and minihits classes.

So here are the attributes of of a minihit:
```
struct MinimizerHit {
    uint32_t read_id;
    uint32_t read_start_position;
    uint32_t prg_id;
    prg::Path prg_path;
    uint32_t kmer_node_id;
    bool is_forward;
}
```
It represents the coordinates of a match between a kmer in a read and a kmer in a PRG.

We need the `read_id` and `read_start_position`, these are not available elsewhere. When a read is sketched, a set of minimiers is created, these are used to define hits then the set is destroyed.

The `prg_id` and `prg_path`  and `kmer_node_id` are all included in the MiniRecord struct as well, and these are stored in the index. In `compare`, the index is kept to the end at the moment, so there would be no problem with **replacing these three with a pointer to the MiniRecord**. In `map`, it looks like I clear the index earlier, so some care would need to be taken to make sure that the coverage information has been added to the kmergraph etc before hand.

The bool is necessary and describes the relative orientation of the minimiser and minirecord (same or different).

Second thing to consider, the attributes of the MinimizerHits class, which stores these hits:
```
class MinimizerHits {
public:
    std::unordered_set<MinimizerHitPtr> uhits;
    std::set<MinimizerHitPtr, pComp> hits;
}
```

To speed things up, I have added hits first to the unordered set. As I loop through reads, when the unsorted hits set gets to a certain size, these are sorted and added to hits. The uhits set is then cleared and the process continues.
Possible issues:
1. uhits is never resized after being cleared. 
2. hits is never resized after being cleared.
3. Unordered_set and set may not be the most memory efficient (or fastest) way to store these things.

**Comment by leoisl** [comment]
Will go through this when learning pandora map, thanks for the detailed description and hints!
