### ISSUE TITLE
Currently not possible to paralellize on samples in pandora compare

### ISSUE THREAD

**Issue by leoisl** [rmcolq/pandora#138]
We were parallelizing on samples in compare (since it receives many samples) and on reads in map (since we receive 1 sample only, but with many reads). Parallelizing on samples in compare makes it run fast, and one of the loops we were parallelizing is:

https://github.com/rmcolq/pandora/blob/5356466d645172171df24009612153b65716176c/src/compare_main.cpp#L310-L384

But this parallelization was wrong: there is an iteration dependency that I missed. I then falled back to parallelize on reads also in compare (each sample is treated one at a time, but the reads of a sample are processed in a multithreaded way) in https://github.com/leoisl/pandora/commit/91ad421ce5579bb8218800d4706966cedc2b2017 . This is 2-5 times slower (in the 16 samples dataset at 20x), but we generate then correct results. The only dependency that is not allowing us to parallelize on samples is the `e_rate` (error rate) variable:

https://github.com/rmcolq/pandora/blob/5356466d645172171df24009612153b65716176c/src/compare_main.cpp#L104

 It is given an initial value, depending on the parameters given to compare. The thing is: after processing the first sample, the error rate **might get updated** at 

https://github.com/rmcolq/pandora/blob/5356466d645172171df24009612153b65716176c/src/compare_main.cpp#L348

The updated error rate is then used to map the second sample at 

https://github.com/rmcolq/pandora/blob/5356466d645172171df24009612153b65716176c/src/compare_main.cpp#L326-L331

Then it might get updated again, and will be used in the mapping of the third sample and so on. So this is an iteration dependency: the processing of the i-th iteration depends on a value defined in the (i-1)-th iteration, and thus we can't parallelize the loop as a whole (only some parts of it). I am wondering if this should be kept like this or if there is a way around it which will allow us to fully parallelize on samples in pandora compare. Not a big issue though, since this does not seem to be the major bottleneck in pandora compare, and the heaviest part of this loop is processing the reads, which is currently parallelized.

**Comment by iqbal-lab** [comment]
The error rate is dataset/fastq dependent, and ought to be remembered per-sample @leoisl

**Comment by rmcolq** [comment]
Agreed. Was a shortcut and not a good one

Rachel



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by leoisl** [comment]
Just for remembering what we discussed on Slack:  I will keep the code as it is, because we can then compare with the previous version. Once we are sure the new version is stable, then we  proceed to fix this bug.

**Comment by leoisl** [comment]
Update: multithreading on samples will be slightly faster but will potentially use a lot more RAM, so I think it is not worth it - we are more constrained on RAM usage when processing a lot of samples in `pandora compare`. So I'd vote to keep multithreading on reads, as it is now.

So, from this issue remains only solving the minor bug on how the error rate is computed.

**Comment by mbhall88** [comment]
I guess this will also close https://github.com/rmcolq/pandora/issues/93
