### ISSUE TITLE
Logic for number of args passed to map command is incorrect

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#140]
https://github.com/rmcolq/pandora/blob/5356466d645172171df24009612153b65716176c/src/map_main.cpp#L70-L74

The problem here is that if the user passes `pandora map -h` then this causes the error message to be printed, followed by the usage command.  

This still provides the usage menu as requested by the user, so this is a minor bug I guess.

*Note*: when fixing, ensure there is a space before `"arguments"` so it doesn't get blended together with `argc`

**Comment by mbhall88** [comment]
I guess we possibly don't even need this check?

**Comment by rmcolq** [comment]
Could replace with a fail if the necessary arguments have not been specified. I.e. need a panrg and if don't give it present the help before dying.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by mbhall88** [comment]
Yeah, that's the most complete solution. In that case, probably best to handle this issue along with #53

**Comment by leoisl** [comment]
+1 for using `boost::program_options`
