### ISSUE TITLE
Tracking pandora index RAM usage and runtime 

### ISSUE THREAD

**Issue by leoisl** [rmcolq/pandora#149]

**Comment by leoisl** [comment]
@rmcolq runs:

Commit: https://github.com/rmcolq/pandora/commit/84aaaac57c236901f9583f54057076f7bd9e79dc

1/
PRG: `/nfs/leia/research/iqbal/projects/pandora/klebs/holt_gastro/prg/holt2015/combined_genes_igr10/pangenome_PRG.fa`
Command line: `pandora index -w 19 -k 31 -t 16 /nfs/leia/research/iqbal/projects/pandora/klebs/holt_gastro/prg/holt2015/combined_genes_igr10/pangenome_PRG.fa`
Max Memory : 18297 MB (17.8 GB)
Run time : 1747 sec (0.48 h)

2/
PRG: `/hps/nobackup2/iqbal/projects/pandora/ecoli/panrg/ecoli_pangenome_PRG_210619.fa`
Command line: `pandora index -w 19 -k 31 -t 16 panrg/ecoli_pangenome_PRG_210619.fa`
Max Memory : 20352 MB (19.8 GB)
Run time : 3565 sec (1h)

**Comment by leoisl** [comment]
Runtime seems fine, RAM is a little bit worrying, but indexing will not be done as frequently as map and compare. I think the hardest instances will be when augmenting the PRG with denovo sequences, will update this when we get this.

For now setting the priority of this issue to low (feel free to update if indexing should be prioritised).

**Comment by iqbal-lab** [comment]
sounds good. if/when we need to,index RAM can be dropped by indexing genes independently

**Comment by leoisl** [comment]
Closing, outdated. We have better performance tracking with the plots generated to evaluate pandora performance for the paper.
