### ISSUE TITLE
Tracking pandora map RAM usage and runtime 

### ISSUE THREAD

**Issue by leoisl** [rmcolq/pandora#150]
To be done

**Comment by mbhall88** [comment]
Would be great if you could include denovo in this too. I know you haven't looked at it yet, but it will likely be used with map fairly regularly (happy to not do this though if others feel it is no necessary).

**Comment by leoisl** [comment]
I agree, in fact I think it is essential to include de-novo in this performance tracking. This shall be updated after solving https://github.com/rmcolq/pandora/issues/136

**Comment by leoisl** [comment]
Closing, outdated. We have better performance tracking with the plots generated to evaluate pandora performance for the paper.
