### ISSUE TITLE
Use `uint16` for recording coverage information

### ISSUE THREAD

**Issue by leoisl** [rmcolq/pandora#151]
Ok, let's switch to `uint16` for coverage information then - almost no errors and half RAM usage for recording coverage information. Let's go for `uint8` only if RAM becomes a bottleneck.

_Originally posted by @leoisl in https://github.com/rmcolq/pandora/issues/148#issuecomment-506398232_

**Comment by mbhall88** [comment]
I don't think `uint8_t` would be a good idea. It is very common to have nanopore datasets with over 255x coverage.
But absolutely agree with the change to `uint16_t`
