### ISSUE TITLE
Decide on a code format for the whole project

### ISSUE THREAD

**Issue by leoisl** [rmcolq/pandora#154]
Do this the next time we merge `dev` into `master`.

Options are CLion default, Clang format, Michael's attempt on CLion black style.

**Comment by mbhall88** [comment]
Ok so if we are going to make any progress on this we need everyone to **opinionated** and state their preferences. As trivial as this seems on the surface it makes a big difference when we have multiple people working on a codebase.  

There are two things we need to decide on:
1. Formatting engine
    - CLion's inbuilt engine
    - [Clang format](https://clang.llvm.org/docs/ClangFormat.html)
2. Code style (some of the standards are below)
    - [LLVM](https://llvm.org/docs/CodingStandards.html)
    - [Google](https://google.github.io/styleguide/cppguide.html)
    - [WebKit](https://webkit.org/code-style-guidelines/)
    - [Chromium](https://chromium.googlesource.com/chromium/src/+/master/styleguide/c++/c++.md)
    - [Mozilla](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style)
    - Custom format. Generated with something like [this](https://zed0.co.uk/clang-format-configurator/)

[Here](https://github.com/motine/cppstylelineup) is a repository with different versions of the same file formatted with each of the above. Additionally, the links to each style state dos and donts with examples.

**Comment by mbhall88** [comment]
I am going to get the ball rolling and state my preferences.

1. Clang format
2. WebKit

**Comment by leoisl** [comment]
I have a strong preference for Clang formatting engine.

No strong preference on the code style, but I do like the Webkit one, so +1 for these options!

**Comment by rmcolq** [comment]
Looking at the Webkit example, it looks relatively similar to what I've been doing by default (although not consistently). Happy to go with clang formatting engine and Webkit.

**Comment by mbhall88** [comment]
Ok great. Clang format and WebKit it is.  

Each of us can set this up locally quite easily with the [instructions in the jetbrains docs](https://www.jetbrains.com/help/clion/clangformat-as-alternative-formatter.html). 

In addition, we will also need to integrate some kind of linting workflow into our CI [#158] to check PRs to make sure they have been linted. I would also suggest switching on the option in CLion version control that says to reformat code before commiting (see just below [this](https://www.jetbrains.com/help/clion/clangformat-as-alternative-formatter.html#enable-manually) section).
