### ISSUE TITLE
Setup continuous integration

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#158]
I think we should setup continuous integration so that with all the PRs etc. we have going on it will be easy to see whether tests do indeed pass for all changes. With the added benefit that the testing is done in a clean environment. I think for our current case our best free options are the following:
1. [Travis CI](https://travis-ci.org/) - the free plan has a 120 minute limit for a single build, but unlimited build minutes across builds. (There's also some perks for students).
2. Migrate the code base to GitLab. GitLab has integrated CI plus a huge bonus that it also has a container registry - meaning we can have the singularity image built within GitLab also. They provide [free access to Ultimate and Gold features for open-source projects and educational institutes](https://about.gitlab.com/2018/06/05/gitlab-ultimate-and-gold-free-for-education-and-open-source/). Additionally, the [GitLab integration tool](https://docs.gitlab.com/ee/user/project/import/github.html#using-the-github-integration) will bring all issues, PRs, wikis, labels etc. across as well.

Please add any other options that I have missed or you feel would be better. Also, if you feel we don't need CI then you can also voice that too.

**Comment by iqbal-lab** [comment]
i guess if it has the features it will win, the gitlab ui is ugly

**Comment by rmcolq** [comment]
We already have Travis CI toggles in the README for master and dev. Although I have a feeling that in some cases the build can fail and it still works

**Comment by rmcolq** [comment]
Wow, the last time Travis actually calculated something for the build was 3 years ago!

**Comment by mbhall88** [comment]
> i guess if it has the features it will win, the gitlab ui is ugly

Interesting, I actually prefer the GitLab UI to the GitHub one.  

So are you saying Travis or GitLab @iqbal-lab ? Couldn't tell from your response.

**Comment by leoisl** [comment]
Continuous Integration really seems to be essential now! In my opinion, we should really do this, but whether we should stay on Github with Travis CI or migrate to GitLab, I don't have any strong preference... Thus I leave this decision mostly to you.

**Comment by rmcolq** [comment]
Personally I'd favour keeping the code where it is an fixing up Travis CI.

**Comment by iqbal-lab** [comment]
That is my preference too, but i am aware i don't know gitlab well. can we discuss when we next meet. i see the container is a win

**Comment by mbhall88** [comment]
Another option to add into the list (although it is in beta) is https://github.com/features/actions
