### ISSUE TITLE
Investigating GATB for de-Bruijn graph analysis

### ISSUE THREAD

**Issue by rffrancon** [rmcolq/pandora#16]
I'm not sure how to properly install GATB so that we can use it as a library. I've opened an issue here: https://github.com/GATB/gatb-core/issues/21

This is the work that we've done so far on this issue: https://github.com/mbhall88/pandora/commit/346c4f775dbd1fc60239890349957b5eaba7d458

**Comment by mbhall88** [comment]
Merged into `dev` branch 4cd090ece91fd03d230730d69121bb8d5ecad586
