### ISSUE TITLE
Log level is not parsed correctly

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#160]
With the current way we parse the log level we actually only allow for debug or info level. We need to also allow for warning, error, and trace.

We get the level from the user here 
https://github.com/rmcolq/pandora/blob/493be42f61898ce0382597e534f71894a19c1da1/src/map_main.cpp#L256-L261

But then we effectively only pay attention to it if it is debug

https://github.com/rmcolq/pandora/blob/493be42f61898ce0382597e534f71894a19c1da1/src/map_main.cpp#L316-L319

**Comment by leoisl** [comment]
I think `boost::program_options` deals with setting the log level from an argument: just logging this when we are back to this issue: https://stackoverflow.com/a/30298255/5264075
