### ISSUE TITLE
Code improvements TODO for paper

### ISSUE THREAD

**Issue by leoisl** [rmcolq/pandora#161]
1. speed up the last parts of denovo;
2. speed up `make_prg` (c++ reimplementation + other performance improvements). denovo pipeline keeps being: 1) dealign the MSA; 2) add the paths; 3) redo the MSA; 4) redo the PRG (`make_prg`); 5) redo the index (see https://github.com/mbhall88/pandora_simulations/blob/master/rulegraph.png?raw=true );
3. if in the analysis we need to compare thousands of samples, we have to split the big PRG in genes and combine the results after;

**Comment by iqbal-lab** [comment]
We don't need item 3 for the paper.

**Comment by leoisl** [comment]
Updated:
1. speed up the last parts of denovo;
2. speed up make_prg (c++ reimplementation + other performance improvements). denovo pipeline keeps being: 1) dealign the MSA; 2) add the paths; 3) redo the MSA; 4) redo the PRG (make_prg); 5) redo the index (see https://github.com/mbhall88/pandora_simulations/blob/master/rulegraph.png?raw=true );

**Comment by mbhall88** [comment]
Closing this as this issue has now been broken up into #163 and #164
