### ISSUE TITLE
Host image on dockerhub

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#165]
Singularity Hub is starting to seem like it won't be a good long-term solution for hosting our container images (it has currently been down all week for instance).  

I think [Docker Hub](https://www.docker.com/products/docker-hub) is probably the most versatile solution. We kill two birds with one stone too as we support Docker and Singularity from one location. Additionally, Docker Hub is much more widely used and therefore is maintained a lot better.

**Comment by leoisl** [comment]
I agree on this. Should we also provide a portable linux binary (e.g. download and execute the binary), like it was done in kallisto (see https://pmelsted.wordpress.com/2015/10/14/building-binaries-for-bioinformatics/ ). I did this for DBGWAS, it worked fine.

**Comment by rmcolq** [comment]
If you are happy to build it, YES

**Comment by leoisl** [comment]
Yep, I have already the scripts, so it would be just copy to pandora repo, and change one thing or another I guess...
