### ISSUE TITLE
Failing localPRG test

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#185]
https://github.com/rmcolq/pandora/blob/67a709a6d2ac27e0adad125469251635032a6167/test/localPRG_test.cpp#L1601-L1611

This test is failing on my machine with the following error

```
/home/michael/Projects/pandora/test/localPRG_test.cpp:1610: Failure
Expected equality of these values:
  actual
    Which is: 23
  expected
    Which is: 22
```

I have not touched this file since the latest commit to Rachel's `dev` branch. I am on https://github.com/mbhall88/pandora/commit/b32091f19a567b60bf99f97eaa2372ceb055deb1

**Comment by mbhall88** [comment]
Hmmm, that's concerning - they all now pass...

**Comment by mbhall88** [comment]
Reopening this as I am still getting this failing intermittently. Is there something non-deterministic about this function?

**Comment by leoisl** [comment]
Thanks, will take a look soon!

**Comment by leoisl** [comment]
In 1 out of 20+ unit tests full suite runs, I get this error also... I am wondering if we are accessing uninitialised values somehow, will check with `memcheck`
