### ISSUE TITLE
Reformat project with ClangFormat

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#188]
Continuing discussion from https://github.com/rmcolq/pandora/pull/186#pullrequestreview-303213542

> The PR is actually small (if I did not miss anything). What makes it very large is the Clang formatting (I guess >90% of the lines are formatting changes, not code logic changes). It made reviewing complicated since sometimes I would skip some parts of the review by rapidly scanning the changes which seemed like only Clang formatting changes.

> I guess we acknowledged this after making these commits (some months ago) and decided to make a big PR with only Clang formatting changes, and then proceed from there. I am willing to do this as soon as possible so that it is easier to review future code, but we still have some WIP branches in pandora. If we apply the Clang formatting in the whole code base now, I guess we will get a bunch of conflicts when merging these branches, which might be hard to solve. So we are thinking on applying Clang Formatting when the code is in a stable state (i.e. probably when finishing the paper).

> **What do you think about this? When should we apply Clang formatting?**

So team, when are we going to do this? I think we have dumped a lot of issues in the "waiting-until-the-code-is-stable" basket. I vote for biting the bullet and doing it.

**Comment by rmcolq** [comment]
Assuming CLion does most of the work anyway so it doesn't take very long, I'm ok with that.

**Comment by mbhall88** [comment]
It's probably just easier to run the actual `clang-format` program on the whole directory. Along with the commit for this formating change, we could also add in a CI requirement/check that PRs have been formatted.

**Comment by mbhall88** [comment]
Actually, as per usual, sadly the C++ tooling makes this extremely laborious to do (have a CI check for formatting)

**Comment by rmcolq** [comment]
I have a few stale branches and have no plans to try and integrate them just yet because they are so old. I need them for reference when I get back to trying to implement those methods. The only current branch I had just printed some extra info to the mosaic fastaq header lines about coverage statistics. Was more for the purposes of debugging than anything else, and can easily be reapplied once `dev` is reformatted.

**Comment by leoisl** [comment]
I agree, I think we should do this, and if we have to deal with conflicting merges later, we deal with them. But I also think that this is closely related to CI, and to the question if we move to Gitlab or not...
