### ISSUE TITLE
Fix singularity recipe

### ISSUE THREAD

**Issue by leoisl** [rmcolq/pandora#191]
Logging this to be done in the next PR.

Singularity recipe should build `pandora` with `RELEASE_WITH_ASSERTS` build type and we should put the tests back.

**Comment by mbhall88** [comment]
Is this not superfluous given we now have a `Dockerfile`?

**Comment by leoisl** [comment]
Oh, it indeed is, but then we should remove the Singularity recipe or keep it consistent with the `Dockerfile`. Should we push the docker image to dockerhub and update the way we pull the image from singularityhub to dockerhub? The image from singularityhub does not include asserts right now, which is essential (otherwise we might get very weird bugs in case of runtime errors, since they are checked with asserts and not exceptions).

**Comment by mbhall88** [comment]
Well in #170 I said 

> Once this PR is merged, @rmcolq will need to setup automated builds on Docker Hub so the image builds and is stored on there.

Then @rmcolq closed #165 . This would suggest it has been pushed to Docker Hub, but I haven't looked.

**Comment by rmcolq** [comment]
It has been pushed to Dockerhub (I had setup automated builds but it went wrong. It does seem to be building dev now). Are you suggesting having a singularity recipe file which just pulls the dockerhub image?

**Comment by leoisl** [comment]
Oh sorry, I got confused by seeing the `Singularity.pandora` file and I forgot about the `Dockerfile`. I guess we should remove the `Singularity.pandora` file and put in the readme that it is hosted in dockerhub instead of singularityhub?

**Comment by rmcolq** [comment]
Ok, will do.
