### ISSUE TITLE
Solve incompatible genotypes through a dynamic programming algorithm

### ISSUE THREAD

**Issue by leoisl** [rmcolq/pandora#194]
Suppose we have two records `R1_gt_0` and `R2_gt_1`.  `R1_gt_0` genotypes towards the reference (allele 0) and `R2_gt_1` genotypes towards the first alternative allele (allele 1). For simplicity, assume only one sample. These records overlap, and thus they are conflicting and we have to solve this conflict (in `pandora` this is done by making the genotypes compatible). 

Right now, in the code, it works like this:
* If the likelihood of **`R1_gt_0` is higher than `R2_gt_1`**, then `R2_gt_1` genotype is changed from 1 to 0.
* If the opposite happens, the likelihood of **`R2_gt_1` is higher than `R1_gt_0`**, then `R1_gt_0` genotype is changed from 0 to `.`.

I don't understand why we have different behaviours depending on the highest likelihood allele (if it is ref or alt). If we have conflicting records, for me it makes more sense to change the genotype of the lowest likelihood one to `.` (we choose one, and all the others become `.`)... but it seems that the previous described behaviour is intended (i.e. not a bug). Could you shed some light on this?

**Comment by rmcolq** [comment]
If the winner is the reference allele, then setting both records to call the reference allele is completely compatible as the reference path is a single path through the graph

However, we do not know that the alt allele of the two overlapping records are compatible (and I couldn't think of a good way to check). 

e.g.
```
pos, ref, alt
0, AA, TG
1, A, C
```

**Comment by leoisl** [comment]
oh, that cleared all my doubts, thanks a lot!

**Comment by rmcolq** [comment]
Additional thought now - there may be a slight mistake in the old way I do it. While if the likelihood of R1_gt_0 is higher than R2_gt_1, we can perfectly happily set the genotype of R2 to 0, we can't do it in the converse situation ( if the likelihood of R2_gt_0 is higher than R1_gt_1). This is because (as the records are sorted, and graph contains bubbles), longer alleles come earlier in the VCF than short ones which share part of the ref allele.
e.g
```
pos, ref, alt, gt, lik
0, AAA, TGG, 1, low
1, A, C, 0, high
2, A, T, 1, high
```

**Comment by leoisl** [comment]
I don't really see the mistake, sorry. In this example, we will find the conflict between R1 and R2, and we will solve it by setting gt of R1 to 0:
```
pos, ref, alt, gt, lik
0, AAA, TGG, *0*, low
1, A, C, 0, high
2, A, T, 1, high
```

Then we detect conflict between R1 and R3, and then solve by setting gt of R1 to `.`:
```
pos, ref, alt, gt, lik
0, AAA, TGG, *.*, low
1, A, C, 0, high
2, A, T, 1, high
```
... and that seems correct to me?

**Comment by rmcolq** [comment]
You are correct! There is no problem

**Comment by leoisl** [comment]
In the current code, to have a conflict between two records we need an overlap of their reference intervals, where the reference interval is `[pos, pos+ref.length)`. As such, we just look at the reference interval, even if the genotyped allele is not the reference.

For example, these two records:
```
pos, ref, alt, gt, lik
1, A, TTTT, 1, low
2, A, GGG, 1, high
```
won't be conflicting as their reference intervals are not conflicting. However, I think they are conflicting because their genotyped alleles are conflicting. I think the correct output for this would be:
```
pos, ref, alt, gt, lik
1, A, TTTT, *.*, low
2, A, GGG, 1, high
```

Is this indeed an issue or not?

**Comment by rmcolq** [comment]
Agreed, they do conflict and that would be the correct output

**Comment by leoisl** [comment]
How do you classify the priority of this issue? Do you think it is rare, and thus the fix should be postponed, or does it have high priority and should be fixed in this refactoring?

**Comment by rmcolq** [comment]
As far as I'm aware, this is rare because I've not seen a case where this has caused bad output.

**Comment by leoisl** [comment]
The best time to implement this fix would be now, as I am adding new tests to `VCF::make_gt_compatible()`, but this would delay the refactoring by some hours (I guess 4-6 hours for this bugfix?). As it is rare, I don't know if I should proceed with the fix, or if you want me to prioritise finishing the refactoring to have the new 4-way ROC curve. I leave the decision to you!

**Comment by rmcolq** [comment]
I say if the best time to implement is now, do it now

**Comment by leoisl** [comment]
There are some pretty complicated corner cases to deal with here. Example:
```
pos, ref, alt, gt, lik
1, A, TTTTTTTTTT, 1, medium
2, A, C, 1, low
3, A, C, 0, high
```
First conflict will be Record 1 vs Record 2 (we look at the genotyped allele now, not the ref). We solve it by setting `.` to Record 2 gt:
```
pos, ref, alt, gt, lik
1, A, TTTTTTTTTT, 1, medium
2, A, C, *.*, N/A
3, A, C, 0, high
```
Second conflict will be Record 1 vs Record 3. We solve it by setting `0` to Record 1 gt:
```
pos, ref, alt, gt, lik
1, A, TTTTTTTTTT, *0*, medium
2, A, C, ., N/A
3, A, C, 0, high
```
And we are done. But because Record 1 is now genotyped to the reference allele, it does not conflict anymore with Record 2, so we could actually roll back the first conflict solution, reverting the Record 2 genotype from `.` to `1` and we still have a compatible and more accurate VCF:
```
pos, ref, alt, gt, lik
1, A, TTTTTTTTTT, 0, medium
2, A, C, *1*, low
3, A, C, 0, high
```

I think this problem is more complicated than it seems after thinking about it. It seems the highest-likelihood calls must always be included, and it seems to me this problem can be formally modelled as an optimization problem (this is a sketch):

**Problem "make genotypes compatible": Given a locus with a set `R` of records, with each record having a called genotype and likelihood associated with it (we assume only `1` sample for simplicity but wlog), find the set `C` of compatible calls, where `C` is the largest subset of `R` satisfying: 1) there are no conflicting records in `C`; 2) there is no record `r` in `R \ C` such that `r` conflicts with a record `c \in C` and `likelihood(r) > likelihood(c)`.**

This problem definition does not model the requirement that if there are conflicting records, and the winner genotypes towards the ref, the loser should then genotype towards the ref, but I think this is easy to do in a post processing once we computed `C`. I think this problem can be solved through a greedy algorithm. In what follows is a sketch why a greedy algorithm would solve it:

**Let `R_max` be the record having the highest likelihood genotype. `R_max \in C` (we can prove this by contradiction I guess). Thus this problem presents the greedy choice property. Adding `R_max` to `C` will generate two subproblems: 1) make genotypes compatible for the set `R_before`, where `R_before` contains all the records that do not conflict with `R_max`, and that end before `R_max`; 2) same thing, but for `R_after`. These subproblems must be solved optimally (we can prove this, also by contradiction). Thus this problem presents the optimal substructure property, and thus can be solved through a greedy algorithm.**


I am unsure if I wandered too much in this problem, or if I misunderstood/missed sth, or even if this makes sense. If you agree with this formulation, I guess implementing this will take some days, so I will postpone it, and we keep using the current method for now, as it handles correctly most cases it seems.

**Comment by rmcolq** [comment]
Understood. And this greedy solution makes sense to me

**Comment by leoisl** [comment]
The most critical thing is the problem definition. There is nothing you'd like to add or is it precise?

**Comment by rmcolq** [comment]
I'm not sure about point 2) "there is no record r in R \ C such that r conflicts with a record c \in C and likelihood(r) > likelihood(c)."

Suppose r conflicts with both c1 and c2. Then in theory could likelihood(r) > likelihood(c1) and likelihood(r) < likelihood(c2)?

I agree that we want to remove/change the call of the fewest possible to make things compatible. Also I agree with the appropriate result in the example you give.

I'm not entirely sure I understand your solution. Are you suggesting that at each point you parse the remainder of the VCF for the next highest likelihood record and assume we can add it to C. Then modify records in R \ C to be compatible with this new record? 

This would be maximizing the average likelihood of records in C, but may not give the minimal number of changes, or would it?

**Comment by leoisl** [comment]
> I'm not sure about point 2) "there is no record r in R \ C such that r conflicts with a record c \in C and likelihood(r) > likelihood(c)."
> 
> Suppose r conflicts with both c1 and c2. Then in theory could likelihood(r) > likelihood(c1) and likelihood(r) < likelihood(c2)?

You are right about point 2), it is wrong. I think it should be changed from:

2) there is no record `r` in `R \ C` such that `r` conflicts with a record `c \in C` and `likelihood(r) > likelihood(c)`.

to:

**2) for each record `r` in `R \ C` there exists a record `c \in C` such that `r` conflicts with `c` and `likelihood(c) > likelihood(r)`.**

> 
> I agree that we want to remove/change the call of the fewest possible to make things compatible. Also I agree with the appropriate result in the example you give.
> 
> I'm not entirely sure I understand your solution. Are you suggesting that at each point you parse the remainder of the VCF for the next highest likelihood record and assume we can add it to C. Then modify records in R \ C to be compatible with this new record?
> 
> This would be maximizing the average likelihood of records in C, but may not give the minimal number of changes, or would it?

You are right again! I think to give us the minimal number of changes it can't be a greedy choice. Instead of trying just the record with the highest likelihood genotype, we should try all feasible records (i.e. the ones that won't violate the properties)?

**Comment by rmcolq** [comment]
This is a hard problem! I approve of new 2). Right now I have no good solution for how to find C so as to minimize R\C ... trying lots of options also sounds messy, so maybe we have to do the less-result-optimal but more-computationally-optimal greedy approach after all. I think thinking on it some more might help.

**Comment by leoisl** [comment]
Trying to sketch an algorithm:

```
make_gt_compatible(R):
  largest_solution = empty_set() // largest solution yields the minimal number of changes
  for each r in R:
    if r is feasible:
        solution_before = make_gt_compatible(R_before)
        solution_after = make_gt_compatible(R_after)
        solution = solution_before U {r} U solution_after
        if size(solution) > size (largest_solution):
          largest_solution = solution
  return largest_solution
```

`r is feasible` if there is no other `r' in R` such that `r'` conflicts with `r` and `likelihood(r') > likelihood(r)`.

If `R` is represented as a vector of sorted intervals, then we can represent `R_before` and `R_after` as ranges of `R` (e.g. `R[1:4]`). This is the case in pandora. Since the number of different ranges is `O(|R|^2)`, the number of generated subproblems is polynomially bounded and we can solve this problem using a dynamic programming algorithm.

Does this sound better?

**Comment by rmcolq** [comment]
Yes!

**Comment by leoisl** [comment]
We might be missing sth here, we might need to think more about this problem... but I guess we are at least sure it is a hard problem, and the very large majority of cases is solved with what we have already implemented. So I guess we leave this as an enhancement post-paper?

**Comment by iqbal-lab** [comment]
christ

**Comment by iqbal-lab** [comment]
ok i have some comments.
1. i definitely agree this should not be attempted now, and even if it was easy we should not do it now. We should make atomic simple commits/fixes and test their impact on the 4way. so we should merge in the basic refactoring and test.
2. this is hard and it would be good to measure how much it impacts us
3. we should not be working on maximising likelihoods and comparing likelihoods of different choices - i think it makes sense to look at a posterior where we use a prior which is simply about how much coverage we expect, which allows us to downweight things where we have very low coverage, and distinguish between alternate paths where one has v low and other sensible coverage. 
4. in your complex optimisation, some regions should not impose constraints if the level of support on them is too low.

**Comment by mbhall88** [comment]
> In the current code, to have a conflict between two records we need an overlap of their reference intervals, where the reference interval is `[pos, pos+ref.length)`. As such, we just look at the reference interval, even if the genotyped allele is not the reference.
> 
> For example, these two records:
> 
> ```
> pos, ref, alt, gt, lik
> 1, A, TTTT, 1, low
> 2, A, GGG, 1, high
> ```
> 
> won't be conflicting as their reference intervals are not conflicting. However, I think they are conflicting because their genotyped alleles are conflicting. I think the correct output for this would be:
> 
> ```
> pos, ref, alt, gt, lik
> 1, A, TTTT, *.*, low
> 2, A, GGG, 1, high
> ```
> 
> Is this indeed an issue or not?

and then from @rmcolq 

> Agreed, they do conflict and that would be the correct output

These _are_ compatible?!

**Comment by rmcolq** [comment]
Not sure which bit you are querying. @leoisl provided an example of conflicting records that would not be detected with my definition. I agreed that they did confict despite not meeting my definition. @leoisl provided an example of the fix for those two records and I agreed that with the modified genotype call (with a '.' for the first record), they are now compatible. 
Or are you saying that you think they do not conflict? The 'pos' field is different...

**Comment by mbhall88** [comment]
What I'm saying is that

```
pos, ref, alt, gt, lik
1, A, TTTT, 1, low
2, A, GGG, 1, high
```
is compatible. i.e this would result in a theortetical sequence `A1A12A2A` becoming `A1TTTT12GGG2A`

**Comment by leoisl** [comment]
What @mbhall88 says seems to be correct to me.

**Comment by rmcolq** [comment]
And me... Why did we miss this...?

**Comment by leoisl** [comment]
It was my misunderstanding of VCF records I'd say. The dynamic programming algorithm could still be useful, we just need to redefine when does a record conflict with another. It could be used to make the VCF compatible with the minimal number of changes (current algorithm does not guarantee this), but it seems to be a lot of work for a small gain? Should this now have low priority?

**Comment by leoisl** [comment]
Ahm, it seems that we still have an issue here, even when we just look at the ref. Let's take a back one of your first examples and change it a little bit
```
pos, ref, alt, gt, lik
1, AAA, TGG, 1, medium
2, A, C, 0, low
3, A, T, 1, high
```

We will detect conflict between Record1 and 2, and will change gt of Record2 to `.`:
```
pos, ref, alt, gt, lik
1, AAA, TGG, 1, medium
2, A, C, *.*, low
3, A, T, 1, high
```

Then we detect conflict between Record1 and 3, and will change gt of Record 1 to `.`:
```Ahm, it seem
pos, ref, alt, gt, lik
1, AAA, TGG, *.*, medium
2, A, C, ., low
3, A, T, 1, high
```

At this point, Record2 could actually be rolled back to have gt `0`, as it does not conflict with Record1 anymore as its GT is `.`.

**Comment by mbhall88** [comment]
So we need something that clusters incompatible pairs first, and then figures out how to make them incompatible in such an order that we don't end up with things being nullified that could be compatible in the end,

**Comment by iqbal-lab** [comment]
I think this is now out of date and can be closed?
