### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#203]
This Epic is aimed at grouping together issues relating to all stages of `pandora` installation. Including compiling, linking, installing, `cmake`, `conan` etc.

**Comment by giuferrero** [comment]
Hi,
I found Pandora very interesting for my studies but I had problems with the installation.
Specifically, when I run the command `sudo make` from the build folder I received the following message:

[ 45%] Built target gtest
[ 45%] Building CXX object test/CMakeFiles/pandora_test.dir/utils_test.cpp.o
/bactell/opt/pandora/test/utils_test.cpp: In function ‘void setup_index(std::vector<std::shared_ptr<LocalPRG> >&, std::shared_ptr<Index>&)’:
/bactell/opt/pandora/test/utils_test.cpp:740:44: error: declaration of ‘std::vector<std::shared_ptr<LocalPRG> > prgs’ shadows a parameter
     std::vector<std::shared_ptr<LocalPRG>> prgs;
                                            ^~~~
/bactell/opt/pandora/test/utils_test.cpp:750:10: error: declaration of ‘auto index’ shadows a parameter
     auto index = std::make_shared<Index>();
          ^~~~~
/bactell/opt/pandora/test/utils_test.cpp:739:58: warning: unused parameter ‘prgs’ [-Wunused-parameter]
 void setup_index(std::vector<std::shared_ptr<LocalPRG>> &prgs, std::shared_ptr<Index> &index){
                                                          ^~~~
/bactell/opt/pandora/test/utils_test.cpp:739:88: warning: unused parameter ‘index’ [-Wunused-parameter]
 void setup_index(std::vector<std::shared_ptr<LocalPRG>> &prgs, std::shared_ptr<Index> &index){
                                                                                        ^~~~~
test/CMakeFiles/pandora_test.dir/build.make:1838: recipe for target 'test/CMakeFiles/pandora_test.dir/utils_test.cpp.o' failed
make[2]: *** [test/CMakeFiles/pandora_test.dir/utils_test.cpp.o] Error 1
CMakeFiles/Makefile2:199: recipe for target 'test/CMakeFiles/pandora_test.dir/all' failed
make[1]: *** [test/CMakeFiles/pandora_test.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

Have can I solve this?
Thank you very much in advance.
Bests regards,
Giulio

**Comment by rmcolq** [comment]
Hi Giulio! Some of the current dependencies of pandora make installation a bit problematic on a number of computers. We are working on improving this. Are you able to use a containerised (singularity or docker) version? This is the most reliable way to install pandora.
If not, can you confirm what OS you are installing on and whether you installed the specific versions of zlib and boost as outlined in the Installation section of the README?

**Comment by giuferrero** [comment]
Hi,
The OS is an Ubuntu 18.04.4 LTS.  The zlib version is 1.2.11 while the boost version is 1.65.1.
I tried the singularity version but running the command gives a blurry screen that is not readable.
I will try with docker. Where can I find the commands for running the docker image?
Thank you very much.
Bests,
Giulio

**Comment by mbhall88** [comment]
Hi @giuferrero 
Apologies, the [latest container instructions are currently on the `dev` branch](https://github.com/rmcolq/pandora/tree/dev#installation) (not master). The following command should allow you to run pandora

```
singularity exec docker://rmcolq/pandora:latest pandora --help
```

Regarding your previous issue with building from source, what version of `gcc` are you using? `gcc --version`

**Comment by leoisl** [comment]
Hello @giuferrero 
Could you also send your `cmake` command and output please?
cheers

**Comment by giuferrero** [comment]
Hi,
I reinstalled all the packages and now the program is working!
Thanks for the help
Bests,
Giulio
