### ISSUE TITLE
Remove local genotyping

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#229]
@iqbal-lab mentioned that we may want to get rid of local genotyping and just make global the only/default option. Is this correct?

**Comment by iqbal-lab** [comment]
I vote yes

**Comment by leoisl** [comment]
I vote for making global genotyping the default, but not removing local genotyping. I think local genotyping does better in some specific cases, and I would like to keep it as I'd like to study this better after paper. I'd like to understand when does the local choice is better than the global choice, and why. And if we can make a mixed genotyping that will get better precision/recall than both

**Comment by iqbal-lab** [comment]
i think it's very hard to use local genotyping and produce variants that are consistent with just one path. Fine to leave global as default from my perspective

**Comment by mbhall88** [comment]
Ok, I made global the default but kept the option to specify local if wanted (I also put a disclaimer than it is intended for development purposes). I also cleaned up (DRY) the genotype function on the VCF class. All in a41530d
