### ISSUE TITLE
Mixing up forward and reverse strand coverage in GFA

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#238]
I have just come across an example where we are (seemingly) mixing up the forward and reverse coverage that is being written to the kmer graph GFAs

https://github.com/rmcolq/pandora/blob/0f1210e6927b905c0a1fe03612ed067d73471851/src/kmergraphwithcoverage.cpp#L371-L372

The signature for this function is 

https://github.com/rmcolq/pandora/blob/9390f0d08ca54e89d9b818d9b9575a59787f95a1/include/kmergraphwithcoverage.h#L81

So we can see that for the second parameter `is_forward` we are passing `0` for the forward coverage and `1` for the reverse coverage.

This is indeed what happens in the implementation at https://github.com/rmcolq/pandora/blob/9390f0d08ca54e89d9b818d9b9575a59787f95a1/src/kmergraphwithcoverage.cpp#L62-L67

I came across this whilst doing some other refactoring so I am happy to make the change, but just wanted to check first in case someone thinks this will cause problems somewhere?

**Comment by leoisl** [comment]
Yeah, it is a bug, but it does not affect paper results as far as I am aware, as we don't process the GFAs with kmer coverage on it at all. This method is just called on `discover_main`:

https://github.com/rmcolq/pandora/blob/9390f0d08ca54e89d9b818d9b9575a59787f95a1/src/denovo_discovery/discover_main.cpp#L296-L300

and `map_main`:

https://github.com/rmcolq/pandora/blob/9390f0d08ca54e89d9b818d9b9575a59787f95a1/src/map_main.cpp#L341-L345

In the pandora version we evaluate in the paper, we just have it in `map_main`, and although we pass the flag to get the Kmer graphs with coverages, we don't post-process it, as we are just interested on the denovo paths. Actually, for the paper, we just need the two coverages, we don't actually need to know from which strand they stem from, so I think even if this bug happens somewhere else, it won't affect paper results.

I am wondering if you would like to move this parameter to the method name (e.g. make `get_covg()` private and have two public methods, `get_forward_covg()` and `get_reverse_covg()` calling it). It gets a little bit verbose, but I prefer a bit more verbosity than such parameter.

Also, there is a test case covering this `KmerGraphWithCoverage::save()` method, and I am pretty sure I introduced this bug, and replicated it further in the test when refactoring the `KmerGraph` class...  Sorry about this

**Comment by mbhall88** [comment]
Sadly, in the process of trying to fix this bug, I have uncovered other situations with mixups in forward and reverse coverage. See an example in the local PRG class https://github.com/rmcolq/pandora/blob/0f1210e6927b905c0a1fe03612ed067d73471851/src/localPRG.cpp#L1452-L1455 (reminder that the second paramter in `get_covg` is called `is_forward`)

I hope that given the summation of these two will remain the same it won't effect results :crossed_fingers:

**Comment by leoisl** [comment]
After some investigation, it seems this bug won't affect results, but forward and reverse coverages will be inverted in `pandora` VCFs and GFAs.
