### ISSUE TITLE
Incorrect usage of SVTYPE

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#249]
The INFO tag `SVTYPE` is reserved for describing structural variants (see [specs](https://samtools.github.io/hts-specs/VCFv4.3.pdf) section 3). However, we use it to describe variant types instead. This could lead to problems with downstream VCF processing tools.

As an example, `cyvcf2` uses the presence of that tag to indicate that a record is a SV. So, for a pandora VCF, every record would be considered an SV.

**Comment by leoisl** [comment]
Closed via https://github.com/rmcolq/pandora/pull/284 and https://github.com/rmcolq/pandora/pull/285
