### ISSUE TITLE
Filtering SNPs

### ISSUE THREAD

**Issue by smb20200615** [rmcolq/pandora#252]
Hello,

I have been trying to test your tool on some isolates to compare phylogeny determined by running pandora on core genome alignments downloaded from PanX with what I would get using tools such as snippy. In theory, the output of the two would be very similar. After running your tool I now have a pangenome matrix and a pangenome VCF. I am struggling to understand the pandora output. I was wondering if you have any guidance regarding how to build trees after running the pandora workflow with denovo variant calling and obtaining a multi-sample vcf from pandora compare. Does it make sense to use clustalo to generate an alignment of the consensus sequence (pandora.consensus.fq.gz) outputted by pandora compare for each genome and feeding that in to iqtree? 

Thank you so much!

**Comment by iqbal-lab** [comment]
The simplest way to do it would be to take your VCF, restrict to genes present in all your samples, strip out the indels, and then convert this to fasta directly (applying the called SNPs to the vcf reference. So you'd get something like this

vcf ref.   AACGT
sample1 AAGGT

because sample 1 has a C->G SNP at position 3, etc

You can then pass into IQtree or whatever tree tool you use.
Does that make sense?

**Comment by smb20200615** [comment]
Thank you for your guidance. And the vcf reference would be pandora.consensus.fq.gz outputted by pandora compare?

**Comment by mpt35** [comment]
I would also appreciate further clarification regarding the question @smb20200615 posted.

**Comment by leoisl** [comment]
Dear @smb20200615 ,

sorry for the delay on answering you. If you ran `pandora compare`, in the output folder you should have two files: `pandora_multisample.vcf_ref.fa` and `pandora_multisample_genotyped.vcf`. The first one is a fasta file with the closest sequences to all your samples, and should be used as the VCF reference to the second file, which contains the variants for each sample described WRT this reference. The file you've been mentioning, `pandora.consensus.fq.gz` is the output of `pandora map`, and takes into account only a single sample, not several samples. For the tree building, we would recommend you to use the files output by `pandora compare`, and restrict to genes present in all your samples (this can be done with the locus presence-absence matrix output by `pandora`, `pandora_multisample.matrix`), remove indels from the VCF (maybe with `bcftools view -I`), then apply the SNP variants of each sample to each of the remaining genes (I think also with `bcftools`). Then I think you can feed these core genes with applied SNPs to a MSA and generate your tree.

Please tell me if this solves your doubt or if you have further doubts!

cheers

**Comment by smb20200615** [comment]
Thank you so much! That worked brilliantly. I could be mistaking but I didn't need to do an MSA. I just fed the SNPs on the core genes to iqtree as iqbal-lab had initially suggested. Thanks again! I want to close this issue but not sure if mpt35 has also resolved their issue?
