### ISSUE TITLE
Original PRG and new PRG dont have the same number of entries

### ISSUE THREAD

**Issue by sskashaf** [rmcolq/pandora#253]
Hello,

Thank you for your wonderful tool. I have been testing it out via pandora workflow and I am getting an error at this step:

```
assert prgs_in_original == prgs_in_new, f"Original PRG ({prgs_in_original}) and new PRG ({prgs_in_new}) dont have the same number of entries!"
```
I looked the prgs_run_status folder and don't see any issues. I am not sure why I have fewer PRGs in the new (2454) compared to the original (3804). I would appreciate your guidance on what you think could possibly be happening and if  I should be worried about this.

Best wishes,
Sara

**Comment by leoisl** [comment]
Dear @sskashaf,

could you please confirm me if you are running https://github.com/iqbal-lab-org/pandora_workflow from https://github.com/iqbal-lab-org/paper_pandora2020_analyses or independently? Could you describe a bit more your use case, and possibly post your `config.yaml` file? Also, it would be really helpful to have your snakemake log file, if possible, and the output files describing the `clustalo` and `make_prg` run status (`all_msas_run_status.txt` and `all_prgs_run_status.txt` inside dir `<output_folder>/<technology>/<coverage>/<subsampling>`, e.g. `pandora_output_pandora_paper_tag1/illumina/100x/random`), and any other files you find relevant. If you want a private channel for further discussions or to send your files, please message me at leandro [at] ebi.ac.uk

cheers

**Comment by sskashaf** [comment]
Apologies I realized it was a mistake on my side! Sorry for taking your time and thank you again for your wonderful tool!
