### ISSUE TITLE
Tidy up mapped reads output

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#258]
When passing `--mapped-reads` to `pandora map` the output from this option is quite messy.

In the output directory we get a directory for each PRG and that directory has 1 fasta file in it. This effectively creates thousands of directories in the output directory. 

I see two possible solutions here:

1. We put all of these fasta files in a single directory called `mapped_read`
2. We put all of the files together into a single fasta file

The disadvantage of option 1 is that we create thousands of individual files, which is not desirable and I think we are trying to cut back on this kind of behaviour. The disadvantage of option 2 is we will need to encode information about the PRG in the fasta entry headers as they are implied by the filename at the moment.

I am in favour of option 2. Does anyone have any other input?

I will wait for the completion of #257 before working on this otherwise we will have conflicts with assert statements.

**Comment by leoisl** [comment]
Also in favour of option 2. Argh, I stopped a bit https://github.com/rmcolq/pandora/pull/257 in favour of exploring some ideas in the new implementation of `make_prg`, should I finish https://github.com/rmcolq/pandora/pull/257 ASAP?

**Comment by mbhall88** [comment]
My other reservation about option 2 is whether it will be thread-safe?

No need to do it ASAP - but bear in mind I will likely be starting on trying to get GCP working in `compare` sometime next week...

**Comment by iqbal-lab** [comment]
@leoisl have you had a chance to discuss with @mbhall88 the level of test coverage needed for 257? I got the impression you're contemplating a range of solutions varying from moderately thorough to insanely thorough, with a difference in development time of over a week.

**Comment by leoisl** [comment]
> My other reservation about option 2 is whether it will be thread-safe?

We can add some synchronization to make it thread-safe if needed

> @leoisl have you had a chance to discuss with @mbhall88 the level of test coverage needed for 257? I got the impression you're contemplating a range of solutions varying from moderately thorough to insanely thorough, with a difference in development time of over a week.

I am doing a moderate test coverage for now, but I have paused the development of the issue to investigate the usage of POA in the reimplementation of `make_prg`. Sorry about that! I am finishing a benchmark today and getting back to #257 still today

**Comment by leoisl** [comment]
https://github.com/rmcolq/pandora/pull/257 finished some time ago, this can be dealt with

**Comment by leoisl** [comment]
We are now outputting SAM files
