### ISSUE TITLE
Discussion: assumptions relating to cluster size expectations and coverage estimation

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#262]
> Disclaimer: I would like this issue to function as a type of "async" meeting.

I recently (re)read Rachel's thesis chapter relating to quasi-mapping and also walked through some of the code relating to this and have found some assumptions I would like to understand better. In particular, there are two assumptions I would like to challenge. I am not saying they are wrong, I would just like to see where the challenge takes us.

### Assumption 1: Setting the minimum cluster size

In setting the minimum cluster size (sub-heading in [Section 4.3.2][thesis]), we define the threshold for the number of hits in a cluster relative to the length of reads and local graphs. As these two lengths can differ from each other, we take the minimum of the two. However, we don't use the length of the read, we actually use the expected density of minimizers in a read of that length, which is `2||read||/w`. (I believe this comes from Section 3.1 of [this paper][density] - correct me if that is wrong Rachel).  
We then account for sequencing errors by multiplying this value by the `exp(-ke)`. Ultimately, this equation is 

![Screenshot from 2021-02-11 20-58-35](https://user-images.githubusercontent.com/20403931/107628131-ef019d80-6cab-11eb-91f7-2a49bb84c902.png)

where *l* is the minimum k-mer path length of the local graph and *s* is the sequence (read).

In reality, we don't quite do this though. The portion of the code that calculates the number of expected hits (prior to accounting for errors) is https://github.com/rmcolq/pandora/blob/815da22867f2bdaa3e3bf40f382be830c1506b0a/src/utils.cpp#L489-L498

and then later https://github.com/rmcolq/pandora/blob/815da22867f2bdaa3e3bf40f382be830c1506b0a/src/utils.cpp#L223-L227

This is where the assumption comes in. We assume that Nanopore reads are **always** longer than local graphs (`expected_number_kmers_in_short_read_sketch` is always set to uint_32 max for nanopore data). I appreciate that for *E. coli* datasets this is probably correct most of the time. But, for Mtb this is certainly *not* the case. I have plenty of samples with a median read length in the range 0.5-2kbp and lots of local graphs longer than that (by a lot in some cases).

**Question 1:** is this a fair assumption, and if not, should we replace it by checking this minimum value for each read?  
**Question 2:** (@rmcolq) In the paper you for the equation for expected density from, they actually use `2||read||/(w+1)`. Did you explicitly leave out the addition of 1 to the window size? Or am I looking at the wrong equation? I know it probably doesn't make a huge difference, but it's more for completeness sake.

From Rachel's (brilliant) thesis (emphasis mine)

> When the minimum size of a cluster is set too low, we have more false positive
local graphs identified as present in the dataset, and also have to handle more noise
downstream when inferring a mosaic sequence and genotyping. **When it is set too
high, we have less sensitivity to discover loci that are present.**

So, I think for Nanopore datasets with low median read lengths or very long loci, we could be losing sensitivity to discover loci.

### Assumption 2: coverage over 1,000 should be discarded

https://github.com/rmcolq/pandora/blob/815da22867f2bdaa3e3bf40f382be830c1506b0a/src/estimate_parameters.cpp#L217-L231

In particular https://github.com/rmcolq/pandora/blob/815da22867f2bdaa3e3bf40f382be830c1506b0a/src/estimate_parameters.cpp#L227

"Magic" numbers always make me nervous. I appreciate that for any bacterial datasets, a k-mer coverage of 1000 or more is craziness. But if we ever want to look at viruses or bacteria/other sequenced at very high depth, this could cause a lot of problems.   
**Question 3:** should we expose this value as a CLI param or set it a little more "dynamically"? 

[thesis]: https://ora.ox.ac.uk/objects/uuid:a8027db9-8d8c-4015-aab6-1371217ccb5c/download_file?file_format=pdf&safe_filename=RachelColquhounThesis.pdf&type_of_work=Thesis
[density]: https://theory.stanford.edu/~aiken/publications/papers/sigmod03.pdf

**Comment by rmcolq** [comment]
Question 1: I think I initially decided not to do for every read because I thought it would take more time/computation. I have no issue with recomputing it if does not impact performance.
Question 2: No, not intentional. Probably didn't do it because all the numbers are a bit approximate anyway, so I didn't think the precision of including the +1 was necessary. By all means include it for completeness.
Question 2.5: It is possible that for Nanopore datasets with low median read lengths or very long loci, we could be losing sensitivity to discover loci. Is this something you think you are seeing?
Question 3: Yes, a parameter instead of a magic number would definitely be better.

**Comment by mbhall88** [comment]
> Question 2.5: It is possible that for Nanopore datasets with low median read lengths or very long loci, we could be losing sensitivity to discover loci. Is this something you think you are seeing?

On my 7 evaluation samples for Mtb I don't seem to find more loci (I find the exact same amount for all 7). But the recall for SNP calls improves.

![image](https://user-images.githubusercontent.com/20403931/107755896-22f1c700-6d6f-11eb-8948-3c68dfac11fb.png)

In this plot, the compass calls are Illumina, bcftools is self-explanatory, "none" is pandora with no filtering (before fix), then "cluster-fix" is with the fix and the same filters as "d3s1g15", cluster-fixg20 is the same filters just with GT_CONF set to 20 instead of 15, and nodenovo is before the fix.

And precision

![image](https://user-images.githubusercontent.com/20403931/107756091-6b10e980-6d6f-11eb-9bf3-ff23cfd6243b.png)

We see now change in indel recall, but see an *increase* in indel precision strangely...

Btw this is using https://github.com/mbhall88/pandora/tree/7bd03f8d4f798063d20e531ca877b3e98a789023 which has a container at `"docker://quay.io/mbhall88/pandora:7bd03f8"`

**Comment by iqbal-lab** [comment]
I don't understand this in many ways

1. What was your fix exactly?
2. You said the fix increases recall but it doesn't seem to?
3. Interesting that indel precision goes up,but you say that after showing a plot labelled as sno precision.  Wrong plot or wrong axis label? Its a big precision increase shown!

**Comment by mbhall88** [comment]
> I don't understand this in many ways
> 
>     1. What was your fix exactly?

We don't assume Nanopore reads are always longer than local graphs. i.e. for all reads, calculate the minimum cluster size as per the equation from Rachel's thesis in Assumption 1 above.

> 
>     2. You said the fix increases recall but it doesn't seem to in that upper plot?

It does. The "cluster-fix" has equivalent filters to "d3s1g15" and so comparing these two is the same as comparing like-for-like i.e. after and before the fix.

> 
>     3. Interesting that indel precision goes up,but you say that after showing a plot labelled as SNP precision, which confused me.  Is it the wrong plot or maybe just a wrong axis label? Its a big precision increase shown!

Sorry, that is a bit confusing. I didn't bother with adding the indel plot as I didn't want to clutter the comment. (I have updated the comment to make this clearer.

**Comment by mbhall88** [comment]
I think this is sorted in #265. closing for now
