### ISSUE TITLE
[Question]  Could genotyping of SNPs of metagenomic reads work?

### ISSUE THREAD

**Issue by matrs** [rmcolq/pandora#283]
Hello, 
this method looks very promising, thanks for the effort to make it easily accessible to all.
I have a question:
If a build a PanRG for a particular specie and try to pseudoalign raw metagenomic reads (potentially reads from thousands of species), could this method work? I'm concerned about the existence of genes in the metagenome that are present in multiple species, which could align to my PanRG and give me variation which isn't actually coming from  my specie of interest, but from different specie(s). Maybe this doesn't matter or there are other potential problems with metegenomes ?

**Comment by rmcolq** [comment]
At the moment we assume that there are no mixtures in the dataset (although this is an extension we would like to work on in the future sometime). So genes which are repeated several times in different forms within the dataset will get one "consensus" output which is unlikely to be accurate. You could map gene consensus sequences back to a de novo metagenomic assembly of your dataset and use this to filter genes that map with a high enough quality/uniquely to the part of the assembly corresponding to your species of interest. Although I would have very little confidence of there not being some sort of a mixture of the species of interest within the metagenomic dataset.

**Comment by matrs** [comment]
I see, thank you for your response, this information It's really helpful.
