### ISSUE TITLE
Haplotype phasing and coverage info in VCF

### ISSUE THREAD

**Issue by gavinmdouglas** [rmcolq/pandora#286]
Hi there,

I'm interested in using the coverage info of alleles in the VCF to phase haplotypes for individual genes. I'm planning on doing this by parsing the coverage info of all alleles at sites with SNPs and inputing these coverage information to StrainFinder.

First off, do you think this would be inappropriate to do with the SNPs output in the "multisample_consensus.vcf" file for any reason?

Second, if it does make sense to perform phasing with this data, would you recommend that I sum the MEAN_FWD_COVG and MEAN_REV_COVG values per alternative allele? Or would the other coverage values make more sense to use, such as the SUM_FWD_COVG and SUM_REV_COVG?

All the best,

Gavin

**Comment by rmcolq** [comment]
Actually thinking about it some more... given that the underlying assumption at present is that samples are clonal, we only give coverage at sites along/close to the consensus path for that sample. We do not then fill in coverage information for more distant sites (it would involve enumerating all paths through the graph which would be a computational explosion). If you are suggesting using StrainFinder, my guess is that your sample is not clonal, and that this "patchy" coverage information will not be so useful for you?

**Comment by iqbal-lab** [comment]
I dunno, it might still wprk

**Comment by iqbal-lab** [comment]
basically, my guess is, most of the time, the multiple strains will be expressible as SNPs off a single consensus path.
Gavin - basically we're worrying essentially whether it is even possible to express the variants with respect to one reference. Rachel's concern is that one strain has one sequence in gene X, and a second strain's sequence in that gene is so diverged that it can't really be written as a SNP difference. (Hope i'm not misrepresenting you @rmcolq )

First i think this will mostly be true (they can be SNP differences from a consensus/ref), and plenty enough to separate strains aggregating info across the genome, and second this is an assumption of strainfinder anyway.

**Comment by gavinmdouglas** [comment]
Thanks to both of you for your quick and helpful replies!

Thanks for sharing your concerns - I will keep them in mind. It seems to me that I would run into the same problem based on haplotyping with a standard SNP set that was based on mapping reads to single representative gene sequences. And yes it will be unfortunate to leave out the structural information / clusters of SNPs, but hopefully the single SNPs provide enough information to get basic haplotype information. I'll have a go anyway and see what it looks like!


Thanks,

Gavin
