### ISSUE TITLE
How does pandora handle paired-end Illumina data?

### ISSUE THREAD

**Issue by dandaman** [rmcolq/pandora#290]
Hi,

what is the best strategy for genotyping based on paired-end data in pandora (map/compare). I.e. Is it possible to provide multiple fastqs for a single sample? Just wondering as map seems to report both read and fragment counts in the gfa...

Sry if this is an obvious question or if I have overlooked the respective part of the docs.

Best,
Daniel

**Comment by rmcolq** [comment]
Hi Daniel, sorry we don't currently take advantage of paired end reads in pandora - we recommend that you cat the files together and input that, but all reads are treated as independent.

**Comment by dandaman** [comment]
Hi Rachel,

thanks for the super fast response! I will do as you suggest then.

Best,
Daniel
