### ISSUE TITLE
Define loci sequences in VCF header

### ISSUE THREAD

**Issue by leoisl** [rmcolq/pandora#292]
For some standard VCF tools (e.g. `bcftools`), this might causes issues processing pandora VCFs. For example, `bcftools concat` fails with:

```
The sequence "gene" not defined in the header: output/pandora_multisample_genotyped.vcf
```

**Comment by iqbal-lab** [comment]
leandro - there is no issue here. VCF supports chromosomes, and we can treat genes as chromosomes?

**Comment by leoisl** [comment]
We can and we should. But right now we don't put genes in the header, and standard VCF tools expect this

**Comment by iqbal-lab** [comment]
ah sorry i see what you mean
