### ISSUE TITLE
Move CI from Travis and container building from Quay to GH actions

### ISSUE THREAD

**Issue by leoisl** [rmcolq/pandora#297]
Anyone oppose to this? When merging https://github.com/rmcolq/pandora/pull/296 into `master`, it seems Quay container building was triggered but Travis CI not. So I am wondering if we could move both workflows to GH actions, as we will use a single service for both tasks, and is easier for devs to track the runs as they are reported in the Actions tab in this repo

**Comment by iqbal-lab** [comment]
fine with me, github actions working well for other repos

**Comment by mbhall88** [comment]
totally fine with me

**Comment by leoisl** [comment]
Done
