### ISSUE TITLE
Upgrading pandora required c++ version from c++11 to c++14

### ISSUE THREAD

**Issue by leoisl** [rmcolq/pandora#307]
[Zipios](https://github.com/Zipios/Zipios) requires C++14 minimum, so I am upgrading pandora required C++ version from c++11 to c++14. Hope there is no issue with you, C++14 is already 8 years old.

**Comment by iqbal-lab** [comment]
basically, can we compile on the cluster? i assume yes?

**Comment by mbhall88** [comment]
Do you reckon we could get away with leapfrogging to c++17? From memory there's a lot of nice new features in that version?

**Comment by leoisl** [comment]
Closed via https://github.com/rmcolq/pandora/pull/318
