### ISSUE TITLE
Typo/bug maybe?

### ISSUE THREAD

**Issue by iqbal-lab** [rmcolq/pandora#326]
Should this really say nanopore at the end?

https://github.com/rmcolq/pandora/blob/346266030778ddb8de1a1678d22cc55162027767/src/utils.cpp#L640

**Comment by mbhall88** [comment]
No. `illumina` is a `bool` that just says whether or not we have Illumina data. If we have nanopore, the remove leaves in the cleaning, whereas we don't for Illumina

https://github.com/rmcolq/pandora/blob/945c0255e99ab32fd5b056dc1c16ffdf611ef478/src/noise_filtering.cpp#L453-L472
