### ISSUE TITLE
Error adding hits to kmer graph: minimizer hit kmer node is invalid

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#327]
https://github.com/rmcolq/pandora/blob/945c0255e99ab32fd5b056dc1c16ffdf611ef478/src/pangenome/pangraph.cpp#L310-L313

I've hit this error when running `map` with a minimum cluster size of 4, 5, 6, 7, 8, 9 and 10.

Command

```
pandora map --genotype --local --gt-conf 0 -v -o /hps/nobackup/iqbal/mbhall/drprg/tmp/predict-ERR4821128 -g 4411532
 --max-covg 4294967295 --vcf-refs /hps/nobackup/iqbal/mbhall/drprg/paper/results/drprg/index/w11/k15/genes.fa -t 2 -w 11 -k 15 -c 10 -I -K /hps/nobackup/iqbal/
mbhall/drprg/tmp/predict-ERR4821128/updated.dr.prg /hps/nobackup/iqbal/mbhall/drprg/paper/results/filtered/illumina/PRJEB41201/ERS5311140/ERR4821128/ERR482112
8.filtered.fq.gz
```

I've been using [this binary](https://github.com/mbhall88/pandora/releases/download/0.10.0-alpha.0.1/pandora-linux-precompiled-v0.10.0-alpha.0.1), which is on this branch https://github.com/mbhall88/pandora/tree/0.10.0-alpha.0.1.

**Comment by mbhall88** [comment]
It get's weirder. `discover` runs fine

```
pandora discover -g 4411532 --max-covg 4294967295 -v -o /hps/nobackup/iqbal/mbhall/drprg/tmp/predict-ERR4821128/dis
cover -t 2 -w 11 -k 15 -c 10 -I -K /hps/nobackup/iqbal/mbhall/drprg/paper/results/drprg/index/w11/k15/dr.prg /hps/nobackup/iqbal/mbhall/drprg/tmp/predict-ERR4
821128/query.tsv
```

**Comment by leoisl** [comment]
Hello, sorry for the delay, I will be soon merging some PRs with new improvements to pandora and could look at this issue now. Is it still relevant?

**Comment by mbhall88** [comment]
I'll close it for now and reopen if I can consistently reproduce this. If I rerun the jobs they normally run okay.
