### ISSUE TITLE
Can I use Pandora to do de novo local assembly of regions that have no read coverage when doing a mapping to reference?

### ISSUE THREAD

**Issue by Isoris** [rmcolq/pandora#346]
Hello !

Can I use pandora and give my own gap region which is not in the reference as a loci?

The idea is that pandora denovo would perform a local assembly and fill the gaps ? do you think that it's possible ? I have a reference genome which has a gap, and a dataset of reads from other organisms. 

Here is a picture of mapped reads from the other organism in question to my reference. 

![image](https://github.com/rmcolq/pandora/assets/78720716/7b894c9b-025e-4de4-ae29-1dfc475b0c63)

For instance I would supply this sequence and perform a denovo local assembly with pandora discover?
Then I would merge the denovo pandora variant from the discover into the reference and re-map the reads.

Thank you for your answer.

**Comment by iqbal-lab** [comment]
Hi there.  It sounds a very unnatural problem to solve with Pandora . Why don't you just use racon directly? When hours say your reference genome has a gap, do you mean no reads from your sample map to it? Can't it be a deletion?

**Comment by Isoris** [comment]
The genome I have is recent, and I use it as a reference. However, I also have a collection of older genomes for which I have paired-end reads. These genomes probably have INDELs relative to the reference. The samples are actually quite distant phylogenetically. The heuristic behind this idea is that while most of the genome is already correct, I would not like to use tools like racon, which will correct the whole length of the genome. Ok, I will give racon a try!

Thank you for the advice.

**Comment by iqbal-lab** [comment]
Hi there - you can control what you give racon, you could just give it the region of the genome you want, and the reads you want to give it. hope that helps!
