### ISSUE TITLE
Store gene, interval and sub_lmp string in an object

### ISSUE THREAD

**Issue by rmcolq** [rmcolq/pandora#44]

**Comment by rmcolq** [comment]
I'm planning to use a struct data structure to hold this PanNodePtr, Interval and string. Any alternative suggestions?

**Comment by mbhall88** [comment]
Is this "replacing" what is currently the elements that make up the read overlap coordinates vector?

**Comment by rmcolq** [comment]
No - this is additional. So we would have the ReadCoordinate and the GeneIntervalInfo, and could store a pair of them corresponding to each read which overlaps a given gene interval. A vector (or something else) of these pairs would be retained in memory until we have processed all genes. Then we can run the "save_read_strings_to_denovo_assemble" (or rename to something better) on the whole collection (pangraph) rather than on a per gene basis

**Comment by rmcolq** [comment]
<img width="689" alt="screen shot 2018-10-08 at 15 08 08" src="https://user-images.githubusercontent.com/9866043/46613844-2b38f800-cb0c-11e8-8ef6-de588b177f02.png">

**Comment by rmcolq** [comment]
Added in commit 1489e62dbb73f464f5164ff896de9f12016b5ce6
