### ISSUE TITLE
Clean up CLI parameter parsing

### ISSUE THREAD

**Issue by rmcolq** [rmcolq/pandora#53]
Robyn suggested this as a cleaner way to have parameters and help messages

**Comment by mbhall88** [comment]
Agreed. We could also think about setting it up in such a way as to have unit tests for the CLI parsing too. Docs on how to do CLI parsing with boost can be found [here](https://www.boost.org/doc/libs/1_62_0/doc/html/program_options/tutorial.html)

**Comment by mbhall88** [comment]
Martin suggested this header-only library that looks really neat. https://github.com/CLIUtils/CLI11
