### ISSUE TITLE
Make sure compare command runs

### ISSUE THREAD

**Issue by rmcolq** [rmcolq/pandora#55]
Add tests (multisample dataset)
Update in line with how `map` now works 
- include genotyping
- updates which fix the localPRG as something that doesn't change and creates a copy of kmergraphs within pangraph structure where counts/coverages are added
- see how new vcf structure works with adding samples/reads in this case

**Comment by rffrancon** [comment]
rmcolq [12:57 PM] on slack:
> I have constructed a test case (not tested it in compare) in `/nfs/leia/research/iqbal/rmcolq/projects/pandora_compare/data/test_case`
There is a PRG file: `toy_prg_10_genes.fa`, which I have already indexed with pandora
A VCF_REF file: `toy_prg_10_genes.vcf_ref.fa` (optional)
A read_index file: `toy_read_index.tsv` including the three toy read files of 1000 mapped reads for 3 samples
The sample of 10 genes includes some which were only present in a subset of the 3 samples in a previous pandora run which crashed (so they may all end up being present in all of them), but without running pandora again on each sample (taking 2 hours), I can’t currently do better.

**Comment by rffrancon** [comment]
Got this error on a run:
```
Unable to open fastaq file toy_H125100459.fq
```

The command I ran:
```
bsub.py 10 compare ~/github/pandora/cmake-build-debug/pandora compare -p /nfs/research1/zi/rff/data/pandora/issue_55_test_data/toy_prg_10_genes.fa -r /nfs/research1/zi/rff/data/pandora/issue_55_test_data/toy_read_index.tsv -o /nfs/research1/zi/rff/data/pandora/issue_55_outdir
```

I think it expects `toy_H125100459.fq` to be in the working directory.

**Comment by rffrancon** [comment]
Changed working directory to directory of `toy_H125100459.fq`. Now getting this error:

```
pandora: /homes/rff/github/pandora/src/fastaq.cpp:41: void Fastaq::add_entry(const string&, const string&, const std::vector<unsigned int>&, uint_least16_t, std::__cxx11::string): Assertion `global_covg != 0' failed.
/ebi/lsf/ebi-spool/02/1539700796.3298069: line 8: 143681 Aborted                 /homes/rff/github/pandora/cmake-build-debug/pandora compare -p /nfs/research1/zi/rff/data/pandora/issue_55_test_data/toy_prg_10_genes.fa -r /nfs/research1/zi/rff/data/pandora/issue_55_test_data/toy_read_index.tsv -o /nfs/research1/zi/rff/data/pandora/issue_55_outdir
```

**Comment by rmcolq** [comment]
Bother, that looks like I've got an assert which is incompatible with the low coverage toy dataset (a float is getting cast as an int, and being rounded down to 0).

**Comment by rffrancon** [comment]
Will remove assert and try again. Let me know if that's not a good idea. The assert should be `global_covg > 0` anyway right?

**Comment by rmcolq** [comment]
The assert should be global_covg > 0 as you say, but changing the assert to that will not fix the problem, because if the genome_size is too big, then the estimated cove will be < 1 and this float gets rounded down to 0

**Comment by rffrancon** [comment]
I understand. Is zero coverage OK also? `global_covg >= 0` then?

**Comment by rmcolq** [comment]
Zero covg is not ok. I divide by global_covg.

**Comment by rffrancon** [comment]
OK. Removing the assert wont work on my part then. The test data will need to be modified I suppose. Do you have a clear idea of how to do that?

**Comment by iqbal-lab** [comment]
Just change input file to have many duplicates of same reads. Or somehow set genome size

**Comment by rmcolq** [comment]
Add the input parameter `--genome_size` and set it to something smallish. That should work I think

**Comment by rffrancon** [comment]
What's smallish in this case? `--genome_size=10`?

**Comment by rmcolq** [comment]
A better number here would be of the order 1000

**Comment by rmcolq** [comment]
1. Great no segfaults
2. Not so great it looks like there may not be any useful output:
`Tue Oct 16 16:16:27 2018 Multi-sample pangraph has 0 nodes`

**Comment by rmcolq** [comment]
Part of the problem is line 1456 in `localPRG.cpp`. We are filtering out genes that we find, because we have a very rough estimate of `genome_size` and crude thresholds in this line. What happens if you change the line so that it only filters if you have at least 20x global coverage (or make this a parameter that can be set on the command line), and update the --genome_size to 10000

**Comment by rffrancon** [comment]
Did you expect a different result given the data? Do you think there is an error in the code?

**Comment by rffrancon** [comment]
Tested on sample data and commit 6438488880bf8e6fb396d52f24309385174cc12d. Modified this line: https://github.com/rmcolq/pandora/blob/3ee4d077ada2e99d5f322e29d874be530c7bab67/src/localPRG.cpp#L1363

so that `global_covg > 20`.

No errors and no segfaults. Results seem reasonable according to @rmcolq.

Will now run `compare` command on a much larger data set.

**Comment by rmcolq** [comment]
Larger PRG: `/nfs/leia/research/iqbal/rmcolq/projects/pangenome_prg/ecoli/290818_genes_only/ecoli_pangenome_PRG_290818.fa`
Read index of 3 full read datasets:
`/nfs/leia/research/iqbal/rmcolq/projects/pandora_compare/data/small_real_case/small_cardio_read_index.tsv`

**Comment by rffrancon** [comment]
Executable completed successfully (PRG: `ecoli_pangenome_PRG_290818.fa`, read index: `small_cardio_read_index.tsv`). Results:
```
/nfs/leia/research/iqbal/rff/data/pandora/compare_cmd_test
```

@rmcolq If you have a chance, please check the results.

**Comment by rmcolq** [comment]
Great, looks like it ran successfully but it doesn't quite do what I want it to do.
Things that need to change:
- the filename of `outdirmultisample.matrix` should be fixed
- one vcf including everything, not a directory for each
- we need to be able to regenotype the vcf (if you look at `/nfs/leia/research/iqbal/rff/data/pandora/compare_cmd_test/outdir/GC00000002_17/GC00000002_17.multisample.vcf`, the first sample has "." for every line, which is not informative and I can't off the top of my head think why that would happen). To do this we need to be able to add the coverage information to the vcf for each sample. I do something in map_main, but it may not be easy to apply in the multisample case.
- (applies to both map and compare) pangraph needs to be saved for each sample after the max path has been found for each prg, because we get rid of a few due to low coverage etc.

**Comment by rffrancon** [comment]
OK, let's open new issues to address the points you've raised. The compare command seems to run, therefore this issue will be closed.

**Comment by rffrancon** [comment]
1) the filename of `outdirmultisample.matrix` should be fixed
DONE: https://github.com/rmcolq/pandora/issues/90
