### ISSUE TITLE
Create updated PRG file for the subset of genes found present (including genes found exactly, and those with denovo alleles to be included)

### ISSUE THREAD

**Issue by rffrancon** [rmcolq/pandora#56]
Please improve title.

**Comment by leoisl** [comment]
Is this the cheap addition of new sequences to an existing index, to be used after discovery?

**Comment by rmcolq** [comment]
Can be renamed to be.

**Comment by leoisl** [comment]
The title is fine, I was just wondering if I correctly understood it

**Comment by leoisl** [comment]
Low priority for now (see #23 ).

If de novo pipeline requires, put this into high priority.
