### ISSUE TITLE
Decide if LocalPRG::find_path_and_variants is redundant and can be removed

### ISSUE THREAD

**Issue by rmcolq** [rmcolq/pandora#61]
https://github.com/rmcolq/pandora/blob/3ee4d077ada2e99d5f322e29d874be530c7bab67/src/localPRG.cpp#L1414

**Comment by rffrancon** [comment]
It's not currently used in any of the `dev` branch code. I suggest that it should be removed.

**Comment by rmcolq** [comment]
Go ahead - I agree.
