### ISSUE TITLE
Standardise the use of boost::filesystem for directories and filepaths

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#68]

**Comment by mbhall88** [comment]
Given we want to standardise the use of boost filepaths, it maybe makes sense to standardise filestreams with boost also?  
There aren't necessarily any differences (boost just uses the STL fstreams), but boost's filestreams accept boost paths as arguments (at the moment you have to convert the boost path to a string in order to get fstreams to open it).  
https://www.boost.org/doc/libs/1_32_0/libs/filesystem/doc/index.htm

**Comment by mbhall88** [comment]
I think the best way to "enforce" this throughout the codebase is if we parse the command line options that are paths as `fs::path` objects. It then becomes very apparent when you try to compile, which sections of the code need updating to boost filesystem.

**Comment by leoisl** [comment]
Totally agree with this - we won't need to go scanning the codebase as to where we should update, the compiler will tell us! Nice idea!
