### ISSUE TITLE
Implement boost logging

### ISSUE THREAD

**Issue by rmcolq** [rmcolq/pandora#7]

**Comment by mbhall88** [comment]
I suggest whenever working on a file from now on to replace any `std::cout` statements with `BOOST_LOG_TRIVIAL(<level>)`

**Comment by mbhall88** [comment]
Different options for `<level>` can be found [here](https://www.boost.org/doc/libs/1_62_0/libs/log/doc/html/log/tutorial.html#log.tutorial.trivial)

**Comment by mbhall88** [comment]
We probably need to also add a command line argument for setting the log level? Current I just have it hard-coded in `denovo_discovery::find_candidates`, but that would best be moved out into `map_main.cpp` so it can control all functions call from that file.
https://github.com/rmcolq/pandora/blob/17de8bbade2148b8e8dd329348699352d741359e/src/denovo_discovery/denovo_discovery.cpp#L18

**Comment by mbhall88** [comment]
Is this embedded enough in everyone's code going forward now that we can close this? @rmcolq @rffrancon
