### ISSUE TITLE
Set buffer size in find_interval_in_localpath based on w and k

### ISSUE THREAD

**Issue by rmcolq** [rmcolq/pandora#81]
A problem with current approach to picking intervals for local assembly:
- Suppose we have found a path with low coverage over just a base or two
- At the moment, if we add no padding, we pull out an interval in the local path which may only contain that base or 2 (or could be longer, as we include the whole of a local node at a time)
- If the region of the local path we pull out is smaller than the kmer size, then when we find hits inside the region, there aren’t any
- If we happen to have an interval roughly the same size as our kmer size, the only reads we will pick out segments from are the fraction which did overlap the poorly supported region.
- SO we need to have some default values for the buffer based on the size of w and k.

**Comment by mbhall88** [comment]
The padding size that is used by default now is the denovo kmer size doubled  

https://github.com/mbhall88/pandora/blob/6534f73a8f07477c2bae1d381f3badd530f1f181/src/map_main.cpp#L435

As such I feel this issue is resolved. Obviously reopen if you disagree @rmcolq
