### ISSUE TITLE
Limit the number of paths returned from local assembly

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#95]
It is not very helpful/useful if the number of paths we return from local assembly is massive. Ideally, we only want a handful of paths.  
There are a couple of options:
* Set a hard threshold on the number of paths we allow local assembly to generate. One downside to this is the paths you end up with are essentially in a random order. i.e not the necessarily the most "likely" paths.
* Set a threshold for the number of paths (as above) and if a slice hits this threshold, rerun local assembly but have a harder requirement on coverage on each kmer (i.e increase `g_covg_scaling_factor`)

**Comment by iqbal-lab** [comment]
Another option is set a hard limit and if you hit it, abort and ignore that slice. Which I quote like as a first step
