### ISSUE TITLE
make_dir function relies on assert statement to create a directory

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#96]
The function `make_dir` in `utils.cpp` creates a directory within an assert statement. https://github.com/rmcolq/pandora/blob/f0cb55f47a3c8d8d83952cc3b62baf613df27369/src/utils.cpp#L49
This is problematic as when pandora is compiled with assert statements turned off, the directory is never created, with the flow on effect being pandora exits as it can't read/write files it expects to be able to.

**Comment by mbhall88** [comment]
`boost::filesystem::create_directories(dir)` actually does [all of the checks this function already does](https://www.boost.org/doc/libs/1_53_0/libs/filesystem/doc/reference.html#create_directories) (i.e returns true if dir was created, false if it already exists. Throws an error if there was some other reason the directory could not be created)and therefore I feel this function is probably redundant.

**Comment by mbhall88** [comment]
I started to try and make some changes to fix this but it going to require touching quite a few files. I suggest waiting until all @rffrancon's  PRs are merged before beginning this.

**Comment by rffrancon** [comment]
@mbhall88 Just closed one of my PR. Don't hold back making large scale changes on my account.
